[project]
site_name = "Homelab"
site_description = "My notes on various things"
site_author = "Nicholas Wilde"
site_url = "https://nicholaswilde.io/homelab"
copyright = "Copyright &copy; 2025 Nicholas Wilde"
dev_addr = "0.0.0.0:8000"
repo_name = "nicholaswilde/homelab"
repo_url = "https://github.com/nicholaswilde/homelab"
edit_uri = "edit/main/docs/"
plugins = [
  "search",
  "tags",
  { minify = { minify_html = true } },
]
extra_css = [
  "stylesheets/extra.css",
]

[[project.nav]]
Home = "index.md"

[[project.nav]]
About = [
  { "Development" = "about/development.md" },
  { "Future" = "about/future.md" },
]

[[project.nav]]
Apps = [
  { "Adguard Home Sync" = "apps/adguardhome-sync.md" },
  { "AdGuard Home" = "apps/adguardhome.md" },
  { "Apt-Cacher NG" = "apps/aptcacherng.md" },
  { "aria2" = "apps/aria2.md" },
  { "authentik" = "apps/authentik.md" },
  { "BentoPDF" = "apps/bentopdf.md" },
  { "![beszel](https://github.com/henrygd/beszel/raw/refs/heads/main/beszel/site/public/static/favicon.svg){ width="24" } Beszel" = "apps/beszel.md" },
  { "![title](https://raw.githubusercontent.com/selfhst/icons/400886b4f5cd552ef373e4550cb0be7344402cce/svg/changedetection.svg){ width="32" } Change Detection" = "apps/changedetection.md" },
  { "![ConvertX](https://raw.githubusercontent.com/C4illin/ConvertX/refs/heads/main/public/android-chrome-192x192.png){ width="32" } ConvertX" = "apps/convertx.md" },
  { "![cyberkeygen](https://raw.githubusercontent.com/karthik558/CyberKeyGen/refs/heads/main/public/favicon.png){ width="32" } CyberKeyGen" = "apps/cyberkeygen.md" },
  { "Excalidraw" = "apps/excalidraw.md" },
  { "![filebrowser](https://cdn.jsdelivr.net/gh/selfhst/icons/svg/file-browser.svg){ width="32" } File Browser" = "apps/filebrowser.md" },
  { "FrameFi" = "apps/frame-fi.md" },
  { "Gitea" = "apps/gitea.md" },
  { "Home Assistant" = "apps/home-assistant.md" },
  { "homepage" = "apps/homepage.md" },
  { "Immich-Go" = "apps/immich-go.md" },
  { "Immich" = "apps/immich.md" },
  { "Installer" = "apps/installer.md" },
  { "![it-tools](https://github.com/CorentinTh/it-tools/raw/refs/heads/main/public/safari-pinned-tab.svg){ width="32" } IT-TOOLS" = "apps/it-tools.md" },
  { "LocalSend Web App" = "apps/localsend.md" },
  { "![LogWard](https://github.com/logward-dev.png){ width="32" } LogWard" = "apps/logward.md" },
  { "![mailrise](https://raw.githubusercontent.com/YoRyan/mailrise/refs/heads/main/src/mailrise/asset/mailrise-info-128x128.png){ width="32" } mailrise" = "apps/mailrise.md" },
  { "MCP Server" = "apps/mcp-server.md" },
  { "MySpeed" = "apps/myspeed.md" },
  { "![netboot.xyz](https://raw.githubusercontent.com/selfhst/icons/refs/heads/main/png/netboot-xyz-light.png){ width="32" } netboot.xyz" = "apps/netbootxyz.md" },
  { "OpenMediaVault" = "apps/openmediavault.md" },
  { "![patchmon](https://cdn.jsdelivr.net/gh/selfhst/icons/png/patchmon.png){ width="32" } PatchMon" = "apps/patchmon.md" },
  { "Pinchflat" = "apps/pinchflat.md" },
  { "Proxmox" = "apps/proxmox.md" },
  { "qBittorrent" = "apps/qbittorrent.md" },
  { "![reactive-resume](https://raw.githubusercontent.com/AmruthPillai/Reactive-Resume/refs/heads/main/apps/artboard/public/favicon.png){ width="32" } Reactive Resume" = "apps/reactive-resume.md" },
  { "Registry" = "apps/registry.md" },
  { "reprepro" = "apps/reprepro.md" },
  { "![Stirling PDF](https://cdn.jsdelivr.net/gh/selfhst/icons/webp/stirling-pdf.webp){ width="32" } Stirling PDF" = "apps/stirling-pdf.md" },
  { "Traefik" = "apps/traefik.md" },
  { "![unbound][1]{ width="32" } Unbound" = "apps/unbound.md" },
  { "vaultwarden-backup" = "apps/vaultwarden-backup.md" },
  { "Vaultwarden" = "apps/vaultwarden.md" },
  { "![ventoy](https://a.fsdn.com/allura/p/ventoy/icon?83b3cf3559dee8e8a1302821225c2e6076b1e2fded2a1ddc8c229a99eb9efd5a?&w=90){ width="32" } Ventoy" = "apps/ventoy.md" },
  { "![windows](https://cdn.jsdelivr.net/gh/selfhst/icons/png/microsoft-windows.png){ width="32" } Windows 11" = "apps/w11.md" },
  { "Wallos" = "apps/wallos.md" },
  { "![watchyourland](https://cdn.jsdelivr.net/gh/selfhst/icons/png/watchyourlan.png){ width="32"} WatchYourLAN" = "apps/watchyourlan.md" },
  { "webhook" = "apps/webhook.md" },
]

[[project.nav]]
Hardware = [
  { "Apple TV" = "hardware/apple-tv.md" },
  { "ASUS Chromebook Plus CX34" = "hardware/asus-chromebook-plus-cx34.md" },
  { "Chromecast" = "hardware/chromecast.md" },
  { "Digital Picture Frame" = "hardware/digital-picture-frame.md" },
  { "HP ProDesk 600 G3 SFF" = "hardware/hp-prodesk-600-g3-sff.md" },
  { "Lenovo ChromeBook Flex 5" = "hardware/lenovo-chromebook-flex-5.md" },
  { "LG Smart Appliances" = "hardware/lg-appliances.md" },
  { "LilyGo T-Dongle S3" = "hardware/lilygo-t-dongle-s3.md" },
  { "Intel NUC" = "hardware/nuc.md" },
  { "Roborock Vacuum" = "hardware/roborock.md" },
  { "Raspberry Pi Zero W" = "hardware/rpi0.md" },
  { "Raspberry Pi 1 Model B+" = "hardware/rpi1.md" },
  { "Raspberry Pi 2" = "hardware/rpi2.md" },
  { "Raspberry Pi 4 8GB" = "hardware/rpi4.md" },
  { "Raspberry Pi 5 16GB" = "hardware/rpi5.md" },
  { "UniFi" = "hardware/unifi.md" },
  { "Wyze Cams" = "hardware/wyze-cam.md" },
]

[[project.nav]]
"Operating Systems" = [
  { "Chrome OS" = "os/chromeos.md" },
  { "DietPi" = "os/dietpi.md" },
  { "Raspberry Pi OS" = "os/rpios.md" },
]

[[project.nav]]
Tools = [
  { "Apprise" = "tools/apprise.md" },
  { "Autofs" = "tools/autofs.md" },
  { "bat" = "tools/bat.md" },
  { "cheat" = "tools/cheat.md" },
  { "Google Conductor" = "tools/conductor.md" },
  { "docker-volume-backup" = "tools/docker-volume-backup.md" },
  { "duf" = "tools/duf.md" },
  { ".env Files" = "tools/env-files.md" },
  { "eza" = "tools/eza.md" },
  { "fd" = "tools/fd.md" },
  { "fzf" = "tools/fzf.md" },
  { "Gemini CLI Commands" = "tools/gemini-commands.md" },
  { "![gemini](https://cdn.jsdelivr.net/gh/selfhst/icons/png/google-gemini.png){ width="32" } Google Gemini CLI" = "tools/google-gemini-cli.md" },
  { "Google Jules" = "tools/google-jules.md" },
  { "jinja2-cli" = "tools/jinja2-cli.md" },
  { "LocalSend Go" = "tools/localsend-go.md" },
  { "LocalSend" = "tools/localsend.md" },
  { "[LVM][9]" = "tools/lvm.md" },
  { "micro" = "tools/micro.md" },
  { "[pass](https://www.passwordstore.org/)" = "tools/pass.md" },
  { "PVE Sync" = "tools/pve-sync.md" },
  { "pvetui" = "tools/pvetui.md" },
  { "![rclone](https://cdn.jsdelivr.net/gh/selfhst/icons/png/rclone.png){ width="32" } rclone" = "tools/rclone.md" },
  { "restic" = "tools/restic.md" },
  { "ripgrep" = "tools/ripgrep.md" },
  { "sd" = "tools/sd.md" },
  { "SOPS" = "tools/sops.md" },
  { "![syncthing](https://cdn.jsdelivr.net/gh/selfhst/icons/png/syncthing.png){ width="32" } Syncthing" = "tools/syncthing.md" },
  { "Task" = "tools/task.md" },
  { "tmux" = "tools/tmux.md" },
]

[[project.nav]]
Travel = "travel.md"

[[project.nav]]
Reference = [
  { "Cheatsheet" = "reference/cheatsheet.md" },
  { "Emoji" = "reference/emoji.md" },
  { "Tags" = "reference/tags.md" },
]

[project.extra]
social = [
    { icon = "fontawesome/solid/house", link = "https://nicholaswilde.io/" },
    { icon = "fontawesome/brands/github", link = "https://github.com/nicholaswilde" },
    { icon = "fontawesome/brands/twitter", link = "https://twitter.com/nicholascwilde" },
    { icon = "fontawesome/brands/instagram", link = "https://www.instagram.com/wildewoodworking/" },
    { icon = "fontawesome/brands/linkedin-in", link = "https://www.linkedin.com/in/nicholaswilde" },
    { icon = "fontawesome/brands/facebook", link = "https://www.facebook.com/nicholas.wilde/" },
    { icon = "fontawesome/brands/keybase", link = "https://keybase.io/nicholaswilde" },
    { icon = "fontawesome/solid/key", link = "https://github.com/nicholaswilde.gpg" },
]

[project.theme]
name = "material"
features = [
    "content.code.copy",
    "content.code.select",
    "content.code.annotate",
    "content.tabs.link",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle = { icon = "material/brightness-auto", name = "Switch to light mode" }

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle = { icon = "material/brightness-7", name = "Switch to dark mode" }

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle = { icon = "material/brightness-4", name = "Switch to system preference" }

[markdown]
extensions = [
    "admonition",
    "abbr",
    "attr_list",
    "def_list",
    "footnotes",
    "meta",
    "tables",
    "md_in_html",
    { "toc" = { permalink = true } },
    { "pymdownx.arithmatex" = { generic = true } },
    { "pymdownx.betterem" = { smart_enable = "all" } },
    "pymdownx.caret",
    "pymdownx.critic",
    "pymdownx.details",
    { "pymdownx.emoji" = { emoji_index = "material.extensions.emoji.twemoji", emoji_generator = "material.extensions.emoji.to_svg" } },
    { "pymdownx.highlight" = { anchor_linenums = true, line_spans = "__span", pygments_lang_class = true } },
    "pymdownx.inlinehilite",
    "pymdownx.keys",
    { "pymdownx.magiclink" = { repo_url_shorthand = true, user = "nicholaswilde", repo = "homepage" } },
    "pymdownx.mark",
    { "pymdownx.snippets" = { base_path = [ "./pve", "./docker", "./vm", "./docs", "./lxc", "./tools" ] } },
    "pymdownx.smartsymbols",
    { "pymdownx.superfences" = { custom_fences = [ { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" } ] } },
    { "pymdownx.tabbed" = { alternate_style = true } },
    { "pymdownx.tasklist" = { custom_checkbox = true } },
    "pymdownx.tilde",
]
