---
http:
 #region routers 
  routers:
    logward:
      entryPoints:
        - "websecure"
      rule: "Host(`logward.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: logward
    logward-backend:
      entryPoints:
        - "websecure"
      rule: "Host(`logward.l.nicholaswilde.io`) && (PathPrefix(`/api`) || PathPrefix(`/health`))"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: logward-backend
#endregion
#region services
  services:
    logward:
      loadBalancer:
        servers:
          - url: "http://192.168.2.195:3000"
        passHostHeader: true
    logward-backend:
      loadBalancer:
        servers:
          - url: "http://192.168.2.195:8080"
        passHostHeader: true
        healthCheck:
          path: /health
          interval: 10s
#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
