---
http:
 #region routers 
  routers:
    patchmon:
      entryPoints:
        - "websecure"
      rule: "Host(`patchmon.l.nicholaswilde.io`)"
      middlewares:
        - default-headers@file
        - https-redirectscheme@file
      tls: {}
      service: patchmon
#endregion
#region services
  services:
    patchmon:
      loadBalancer:
        servers:
          - url: "http://192.168.2.187"
        passHostHeader: true
#endregion
