---
- Proxmox:
    - Node 01:
        icon: mdi-server
        href: https://pve01.l.nicholaswilde.io
    - Node 03:
        icon: mdi-server
        href: https://pve03.l.nicholaswilde.io
    - Node 04:
        icon: mdi-server-network
        href: https://pve04.l.nicholaswilde.io
- DNS:
    - AdGuardHome 01:
        icon: si-adguard
        href: http://adguard01.l.nicholaswilde.io/
    - AdGuardHome 02:
        icon: si-adguard
        href: http://adguard02.l.nicholaswilde.io/
    - AdGuardHome Sync:
        icon: si-adguard
        href: https://adguard-sync.l.nicholaswilde.io/
    - Traefik:
        icon: si-traefikproxy
        href: https://traefik.l.nicholaswilde.io/    
- IoT:
    - Home Assistant:
        icon: si-homeassistant
        href: http://ha.l.nicholaswilde.io:8123/
    - ESPHome:
        icon: si-esphome
        href: https://esphome.l.nicholaswilde.io/
    - Z-Wave JS UI:
        icon: sh-z-wave-js-ui.png
        href: https://zwave.l.nicholaswilde.io/
    - Terminus:
        icon: https://usetrmnl.com/assets/trmnl--logo--mobile-fd77ffa1253e170dfc7096731ae701f52f3e27ade4d408d35bd31efd56315f4a.svg
        href: https://terminus.l.nicholaswilde.io
    - activepieces:
        icon: sh-activepieces.png
        href: https://ap.l.nicholaswilde.io/
- Networking:
    - Apt-Cacher NG:
        icon: mdi-package-variant
        href: http://aptcache.l.nicholaswilde.io:3142/acng-report.html
    - Modem:
        icon: mdi-server-network
        href: https://modem.l.nicholaswilde.io
    - MySpeed:
        icon: si-speedtest
        href: https://myspeed.l.nicholaswilde.io
    - Shlink:
        icon: sh-shlink.svg
        href: https://shlink.l.nicholaswilde.io
    - UniFi:
        icon: si-ubiquiti
        href: https://unifi.l.nicholaswilde.io
    - Wireguard:
        icon: si-wireguard
        href: https://wireguard.l.nicholaswilde.io
    - Dockflare:
        icon: si-cloudflare
        href: https://dockflare.l.nicholaswilde.io
    - PortNote:
        icon: sh-portnote.svg
        href: https://portnote.l.nicholaswilde.io/
    - PatchMon:
        icon: sh-patchmon.svg
        href: https://patchmon.l.nicholaswilde.io/
- Media:
    - Jellyfin:
        icon: si-jellyfin
        href: https://jellyfin.l.nicholaswilde.io
    - Excalidraw:
        icon: si-excalidraw
        href: https://draw.l.nicholaswilde.io
    - Immich:
        icon: si-immich
        href: https://photos.l.nicholaswilde.io
    - Paperless:
        icon: si-paperlessngx
        href: https://paperless.l.nicholaswilde.io
    - Pinchflat:
        icon: sh-pinchflat.webp
        href: https://pinchflat.l.nicholaswilde.io/
    - ConvertX:
        icon: sh-convertx.webp
        href: https://convertx.l.nicholaswilde.io/
    - Stirling PDF:
        icon: sh-stirling-pdf.svg
        href: https://stirling-pdf.l.nicholaswilde.io/
    - Reactive Resume:
        icon: sh-reactive-resume.svg
        href: https://resume.l.nicholaswilde.io/dashboard/resumes
- Authentication & Security:
    - Authentik:
        icon: si-authentik
        href: http://authentik.l.nicholaswilde.io:9000/
    - CyberKeyGen:
        icon: https://raw.githubusercontent.com/karthik558/CyberKeyGen/refs/heads/main/public/icon-192x192-dark.png
        href: https://cyberkeygen.l.nicholaswilde.io
    - Vaultwarden:
        icon: si-bitwarden
        href: https://vault.l.nicholaswilde.io
- Finance:
    - Wallos:
        icon: sh-wallos.svg
        href: https://wallos.l.nicholaswilde.io
    - Mealie:
        icon: si-mealie
        href: https://mealie.l.nicholaswilde.io
- Monitoring & Analytics:
    - Beszel:
        icon: sh-beszel.svg
        href: https://beszel.l.nicholaswilde.io
    - Change Detection:
        icon: sh-changedetection.png
        href: https://cd.l.nicholaswilde.io/
    - WatchYourLAN:
        icon: sh-watchyourlan.png
        href: https://watch.l.nicholaswilde.io/

- Files & Downloads:
    - Aria2:
        icon: mdi-download
        href: https://aria2.l.nicholaswilde.io    
    - File Browser:
        icon: sh-file-browser.svg
        href: https://fb.l.nicholaswilde.io/
    - Gitea:
        icon: si-gitea
        href: https://gitea.l.nicholaswilde.io/
    - netboot.xyz:
        icon: sh-netboot-xyz-light.png
        href: https://netboot.l.nicholaswilde.io/
    - OpenMediaVault:
        icon: si-openmediavault
        href: http://omv.l.nicholaswilde.io
    - qBittorrent:
        icon: si-qbittorrent
        href: https://qbittorrent.l.nicholaswilde.io/
    - Ventoy:
        icon: https://a.fsdn.com/allura/p/ventoy/icon?83b3cf3559dee8e8a1302821225c2e6076b1e2fded2a1ddc8c229a99eb9efd5a?&w=90
        href: https://ventoy.l.nicholaswilde.io/
- Development Tools:
    - IT-TOOLS:
        icon: https://github.com/CorentinTh/it-tools/raw/refs/heads/main/public/safari-pinned-tab.svg
        href: https://it-tools.l.nicholaswilde.io    
    - VS Code:
        icon: mdi-microsoft-visual-studio-code
        href: https://code.l.nicholaswilde.io/
