---
theme: dark
color: slate
target: _self

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
layout:
  Proxmox:
    style: row
    columns: 3
    icon: si-proxmox
  DNS:
    style: row
    columns: 4
    icon: mdi-dns
  Networking:
    style: row
    columns: 3
    icon: mdi-wall-fire
  Media:
    style: row
    columns: 3
    icon: mdi-camera-iris
  Development Tools:
    style: row
    columns: 3
    icon: mdi-robot
  Files & Downloads:
    style: row
    columns: 4
    icon: mdi-download-box
  IoT:
    style: row
    columns: 3
    icon: mdi-home-automation
  Authentication & Security:
    style: row
    columns: 3
    icon: mdi-shield-key
  Finance:
    style: row
    columns: 2
    icon: mdi-currency-usd
  Monitoring & Analytics:
    style: row
    columns: 4
    icon: mdi-chart-line
  Developer:
    style: row
    columns: 4
    icon: mdi-cog
  Icons & Emoji:
    style: row
    columns: 4
    icon: mdi-emoticon
